# Generated by Django 2.1.2 on 2018-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_id', models.IntegerField()),
                ('symptom_desc', models.CharField(max_length=150)),
            ],
        ),
    ]
