# Generated by Django 2.1.2 on 2018-10-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField()),
                ('issue_name', models.CharField(max_length=100)),
                ('issue_profName', models.CharField(max_length=200)),
                ('specialist_one', models.CharField(max_length=100)),
                ('specialist_two', models.CharField(max_length=100)),
                ('specialist_three', models.CharField(max_length=100)),
                ('treatment_details', models.CharField(max_length=2000)),
            ],
        ),
    ]
