# Generated by Django 2.0.7 on 2019-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
